const ERROR_CODES = {
    BAD_REQUEST: 400,
    NOT_AUTHENTICATED: 403,
    NOT_AUTHORIZED: 401,
    NOT_EXIST: 404,

    INTERNAL_SERVER_ERROR: 500,
    
    VALIDATION_ERROR: 800,
    USER_ALREADY_EXIST: 801,
    USER_NOT_EXIST: 802,
    USER_EMAIL_NOT_VERIFIED: 803,
    USER_ALREADY_VERIFIED: 804,

    // Password reset
    PASSWORD_RESET_FAILED: 810
}

module.exports = ERROR_CODES;